# Generated by Django 3.2.8 on 2021-11-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='project_option',
            new_name='product_option',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='project_option',
            new_name='product_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus'),
            preserve_default=False,
        ),
    ]
